#cloud-config
version: v1
packages_update: true
packages_upgrade: true
packages: 
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-compose-plugin
apt:
  #preserve_sources_list: true
  sources:
    docker-repo:
      keyid: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'  
      source: deb [signed-by=$KEY_FILE] https://download.docker.com/linux/ubuntu jammy stable
users:
    - name: ubuntu
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUYeBc2upEOAkZTBj/wqFQoPRHY3QOGNVHqVrqxlm/nhNBXdpEPL69XiK0MZnnATXAlsZ87TwuM65aDsUnzWGd66BlybYii2VcDGr1F44qQ9AI1nFEx16o0dHHYfivm0qNqchu87fYh0/GqInhsghzNC89oh9Dl6gds+9KDajIA+qGOwmqKHUzl0HHgnsLg+UW0PSKiRyX5ISz7MfwTcRMSbXxS/WRt7J7HSWLpgmqHrEfU69Lzilv+xMRox7rDDwFO0A71/ATy16R1kk/5qMXcVSYfiqqY9ms1ZS7QUgLkOJyVUsZvy1mVyUlmIwFlMscQFQ2BPgU0ZEFn+os43iy9foH0nFDq4st1knT9/RvqsGzTrbp5j+9oirC0t//YmdOzQbFQuexJK6RGQ9b8t616UV9ZcWgn4DalCoPGQFNIqaH5ZfZ7wDWkkcJp2RTIgkE4bwuOXHKKv67RT/CcFjDihczC0oNxO4nt1HD/MFgKO5iTO8u/AY7AoLrhbcqWl8= linux@b112-1
write_files:
  - content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd
    path: /etc/systemd/system/docker.service.d/override.conf
  - content: |
      {"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}
    path: /etc/docker/daemon.json
  - content: |
      net.ipv6.conf.all.disable_ipv6 = 1 
      net.ipv6.conf.default.disable_ipv6 = 1
      vm.max_map_count = 262144
    path: /etc/sysctl.d/custom.conf
runcmd:
  - [sh, -c, 'systemd restart docker']
  - [sh, -c, 'sysctl -p /etc/sysctl.d/custom.conf']